const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cp=require('node:child_process');
const source=fs.readFileSync('dist/services/dailySelection.js','utf8');
function setup(){const c=vm.createContext({window:{}});vm.runInContext(source,c);return c.window.Malsseum.services.dailySelection;}
const plain=x=>JSON.parse(JSON.stringify(x));
test('canonical pool is exactly the 50 approved IDs, independent of other catalogue orders',()=>{const s=setup(),c=vm.createContext({window:{Malsseum:{data:{}}}});for(const f of ['verses','daily-reflections'])vm.runInContext(fs.readFileSync('dist/data/'+f+'.js','utf8'),c);assert.deepEqual(plain(s.pool),require('./fixtures/daily-locked-100.json').selectionPool);assert.deepEqual(plain(s.pool).map(id=>c.window.Malsseum.data.dailyVerseReplacements[id]||id),Object.keys(c.window.Malsseum.data.dailyReflections).slice(0,50));assert.equal(new Set(s.pool).size,50);const app=fs.readFileSync('dist/app.js','utf8'),block=app.slice(app.indexOf('const DailyVerse='),app.indexOf('const PersonalReflections='));for(const reverse of [false,true]){const d=c.window.Malsseum.data,values=new Map();const context=vm.createContext({window:{Malsseum:{data:d,services:{dailySelection:s}}},readableVerses:()=>reverse?[...d.verses,...Object.values(d.dailyVerseOverrides)].reverse():[...d.verses,...Object.values(d.dailyVerseOverrides)],localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)}});vm.runInContext(block,context);assert.equal(vm.runInContext('DailyVerse.get().id',context),s.select().verseId);}});
test('KST date boundary and distinct host timezones use identical results',()=>{const s=setup();assert.equal(s.dateKey(new Date('2026-10-03T14:59:59.999Z')),'2026-10-03');assert.equal(s.dateKey(new Date('2026-10-03T15:00:00Z')),'2026-10-04');const code=source+';console.log(JSON.stringify(window.Malsseum.services.dailySelection.select(new Date("2026-10-03T15:00:00Z"))))';const outputs=['Asia/Seoul','UTC','America/Los_Angeles','Pacific/Honolulu','Europe/London'].map(TZ=>cp.execFileSync(process.execPath,['-e','global.window={};'+code],{encoding:'utf8',env:{...process.env,TZ}}).trim());assert.equal(new Set(outputs).size,1);});
test('same day repeated calls and fresh service instances are stable',()=>{const s=setup(),date=new Date('2026-10-04T00:00:00Z');for(let i=0;i<100;i++)assert.deepEqual(plain(setup().select(date)),plain(s.select(date)));assert.equal(s.select(date).verseId,s.select(new Date('2026-10-04T14:59:59Z')).verseId);});
test('50-day cycles contain every ID once; subsequent cycles differ and boundaries never repeat',()=>{const s=setup();for(let cycle=-2;cycle<1000;cycle++){const order=s.cycleOrder(cycle),next=s.cycleOrder(cycle+1);assert.equal(new Set(order).size,50);assert.deepEqual([...order].sort(),[...s.pool].sort());assert.notDeepEqual(plain(order),plain(next));assert.notEqual(order[49],next[0]);for(let i=0;i<50;i++){const date=new Date(Date.UTC(2026,0,1)+(cycle*50+i)*86400000);assert.equal(s.select(date).verseId,order[i]);}}});
test('canonical current/today updates once; all past history and other personal storage remain byte-identical',()=>{const s=setup(),selection=s.select(new Date('2026-10-04T00:00:00Z')),current='malsseum-annae.daily-verse.v1',history='malsseum-annae.daily-verse-history.v1';const past=Array.from({length:25},(_,i)=>({date:'2026-09-'+String(i+1).padStart(2,'0'),verseId:'old-or-unknown-'+i,extra:'retain'}));const values=new Map([[history,JSON.stringify([...past,{date:selection.date,verseId:'old'}])],[current,JSON.stringify({date:selection.date,verseId:'old'})],['malsseum-annae.personal-reflections.v1','[{"content":"keep","verseId":"old"}]'],['saved','keep bookmarks'],['prayer','keep prayer'],['gratitude','keep gratitude']]);let writes=0;const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>{writes++;values.set(k,v)}};const unrelated=[...values].filter(([k])=>k!==current&&k!==history);s.remember(storage,selection);assert.deepEqual(JSON.parse(values.get(history)).slice(0,-1),past);assert.deepEqual(JSON.parse(values.get(history)).at(-1),{date:selection.date,verseId:selection.verseId});assert.deepEqual(JSON.parse(values.get(current)),{date:selection.date,verseId:selection.verseId});assert.equal(writes,2);for(let i=0;i<10;i++)s.remember(storage,selection);assert.equal(writes,2);assert.deepEqual([...values].filter(([k])=>k!==current&&k!==history),unrelated);});
test('malformed history is never discarded and read-only storage does not affect selection',()=>{const s=setup(),value=s.select(new Date('2026-10-04T00:00:00Z'));let history='{bad';s.remember({getItem:k=>k.includes('history')?history:null,setItem:(k,v)=>{if(k.includes('history'))history=v;}},value);assert.equal(history,'{bad');assert.doesNotThrow(()=>s.remember({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}},value));});
test('production loads common selection before app and Preview review order is unchanged',()=>{const html=fs.readFileSync('dist/index.html','utf8');assert(html.indexOf('services/dailySelection.js')<html.indexOf('src="app.js"'));const {previewApp}=require('../tools/daily-preview-server.cjs');assert(previewApp(fs.readFileSync('dist/app.js','utf8')).includes('DailyVerse.get=()=>readableVerses')); });
