const {chromium}=require('playwright'),assert=require('node:assert/strict'),{createServer}=require('../tools/daily-preview-server.cjs');
(async()=>{const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
for(const width of [319,390])for(const size of ['default','large','xlarge']){
 const page=await browser.newPage({viewport:{width,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(size=>{localStorage.setItem('malsseum-annae.display-name.v1','검수');localStorage.setItem('malsseum-annae.text-size.v1',size)},size);await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('[data-screen=gratitude]').click();const root=page.locator('#gratitude-screen');const today=await root.locator('.is-today').getAttribute('data-date');
 const checkMain=async(date,values)=>{if(await root.locator('.gratitude-form').count()){assert.equal(await root.locator('[type=submit]').textContent(),'감사 달력 보기');assert.match(await root.locator('[role=status]').textContent(),/^감사를 (남겼어요|수정했어요)\.$/);assert.equal(await root.locator('.prayer-calendar').count(),0);await root.locator('[type=submit]').click();}assert.equal(await root.locator('.is-selected').getAttribute('data-date'),date);assert.equal(await root.locator('.is-selected .gratitude-heart').count(),1);assert.equal(await root.locator('.gratitude-entry').count(),values.length);assert.deepEqual(await root.locator('.gratitude-entry p').allTextContents(),values);assert.equal(await root.locator('.gratitude-form,.gratitude-complete').count(),0);assert.equal(await page.locator('#main-content').evaluate(e=>e.scrollTop),0);assert.ok(await root.evaluate(e=>e.scrollWidth<=e.clientWidth+1));};
 await root.getByRole('button',{name:'감사 기록하기',exact:true}).click();assert.equal(await root.locator('h1,.prayer-intro').count(),0);assert.equal(await root.locator('.meditation-back-label').textContent(),'감사 달력 보기');assert.equal(await root.locator('#gratitude-grace').getAttribute('placeholder'),'예) 오늘도 함께해 주셔서 감사해요.');assert.equal(await root.locator('.meditation-journal-status').evaluate(e=>e.getBoundingClientRect().height),0);
 if(width===390&&size==='default')assert.ok(await root.locator('[type=submit]').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('#bottom-nav').getBoundingClientRect().top));
 await root.locator('[type=submit]').click();await root.getByText('감사를 하나 이상 남겨주세요.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('malsseum-annae.gratitude.v1')),null);
 for(const field of ['today','self','grace']){for(const f of ['today','self','grace'])await root.locator('#gratitude-'+f).fill(f===field?field+' 감사':'');assert.equal(await root.locator('.meditation-journal-status').textContent(),'');await root.locator('[type=submit]').click();await checkMain(today,[field+' 감사']);await root.getByRole('button',{name:'수정하기',exact:true}).click();assert.equal(await root.locator('#gratitude-'+field).inputValue(),field+' 감사');}
 await root.locator('#gratitude-today').fill('첫 감사');await root.locator('#gratitude-self').fill('');await root.locator('#gratitude-grace').fill('세 번째 감사');await root.locator('[type=submit]').click();await checkMain(today,['첫 감사','세 번째 감사']);
 assert.equal(await root.locator('.gratitude-item-edit').count(),0);await root.getByRole('button',{name:'수정하기',exact:true}).click();assert.equal(await root.locator('#gratitude-today').inputValue(),'첫 감사');assert.equal(await root.locator('#gratitude-self').inputValue(),'');assert.equal(await root.locator('#gratitude-grace').inputValue(),'세 번째 감사');await root.locator('[type=submit]').click();await checkMain(today,['첫 감사','세 번째 감사']);
 await root.getByRole('button',{name:'이전 달',exact:true}).click();const past=await root.locator('.calendar-day:not(.other-month)').first().getAttribute('data-date');await root.locator('[data-date="'+past+'"]').click();await root.getByRole('button',{name:'감사 기록하기',exact:true}).click();await root.locator('#gratitude-self').fill('지난 감사');await root.locator('[type=submit]').click();await checkMain(past,['지난 감사']);await root.getByRole('button',{name:'수정하기',exact:true}).click();assert.equal(await root.locator('#gratitude-self').inputValue(),'지난 감사');const long='감사한 순간을 기억해요. '.repeat(120);await root.locator('#gratitude-self').fill(long);await root.locator('[type=submit]').click();assert.equal(await root.locator('[role=status]').textContent(),'감사를 수정했어요.');await root.locator('#gratitude-self').fill(long+'추가');assert.equal(await root.locator('[type=submit]').textContent(),'감사 수정하기');assert.equal(await root.locator('[role=status]').textContent(),'');assert.equal(await root.locator('[role=status]').evaluate(e=>e.getBoundingClientRect().height),0);await root.locator('[type=submit]').click();await checkMain(past,[long+'추가']);await root.getByRole('button',{name:'수정하기',exact:true}).scrollIntoViewIfNeeded();assert.ok(await root.getByRole('button',{name:'수정하기',exact:true}).evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('#bottom-nav').getBoundingClientRect().top));await page.reload();await page.locator('[data-screen=gratitude]').click();await checkMain(today,['첫 감사','세 번째 감사']);assert.deepEqual(errors,[]);console.log('PASS gratitude flows',width,size);await page.close();
}}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
