const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(){const store=new Map([['malsseum-annae.personal-prayers.v1','prayer sentinel']]);const c=vm.createContext({window:{Malsseum:{services:{}}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}});vm.runInContext(fs.readFileSync('dist/services/gratitudeJournal.js','utf8'),c);return {journal:c.window.Malsseum.services.gratitudeJournal,store};}
test('gratitude permits any one field, trims blanks, and edits one set per day',()=>{const {journal:j,store}=setup();for(const field of ['today','self','grace']){const saved=j.save('2026-09-29',{[field]:' 고마워요 '});assert.equal(saved[field],'고마워요');assert.equal(j.list().length,1);}assert.equal(store.get('malsseum-annae.personal-prayers.v1'),'prayer sentinel');});
test('gratitude empty submission cannot erase a saved record',()=>{const {journal:j}=setup();j.save('2026-09-29',{today:'감사'});assert.throws(()=>j.save('2026-09-29',{today:'  '}));assert.equal(j.list()[0].today,'감사');});
test('gratitude separates dates, validates calendar dates and preserves creation time',()=>{const {journal:j}=setup();const first=j.save('2026-09-28',{self:'어제'});j.save('2026-09-29',{grace:'오늘'});const edit=j.save('2026-09-28',{self:'어제 수정'});assert.equal(edit.createdAt,first.createdAt);assert.equal(j.list().length,2);assert.throws(()=>j.save('2026-02-30',{today:'x'}));});
test('gratitude corrupted storage is not overwritten',()=>{const {journal:j,store}=setup();store.set(j.key,'broken');assert.throws(()=>j.save('2026-09-29',{today:'x'}));assert.equal(store.get(j.key),'broken');});
test('independent fields preserve legacy records, sibling content and creation date',()=>{const {journal:j}=setup();for(const f of ['today','self','grace'])assert.equal(j.saveField('2026-09-29',f,f)[f],f);const before=j.list()[0];j.saveField('2026-09-29','today','edited');assert.equal(j.list()[0].self,'self');assert.equal(j.list()[0].grace,'grace');assert.equal(j.list()[0].createdAt,before.createdAt);assert.throws(()=>j.saveField('2026-09-29','grace',' '));assert.equal(j.list()[0].grace,'grace');j.save('2026-09-01',{today:'legacy',grace:'old'});j.saveField('2026-09-01','grace','updated');assert.equal(j.list().find(r=>r.date==='2026-09-01').today,'legacy');});

test('clear existing fields removes empty date only',()=>{const {journal:j}=setup();j.saveField('2026-09-01','today','one');j.saveField('2026-09-01','grace','three');j.saveField('2026-09-02','self','other');j.removeField('2026-09-01','today');assert.equal(j.list().find(r=>r.date==='2026-09-01').grace,'three');j.removeField('2026-09-01','grace');assert.equal(j.list().length,1);assert.equal(j.list()[0].date,'2026-09-02');assert.throws(()=>j.saveField('2026-09-01','today',''));});
